on:
  pull_request: 
        types:
         - opened

jobs:
  pr-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Post PR Comment
      uses: kodeklouddemocicd/docker-action-pr-giphy-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

## how to use docker custom/actions on another repo as it were from the marketplace 
## the code allows users to comment gifs after doing a pull request to main branch
## if you commit and push it will save but it wont do the workflow until its pulled to main branch
# 1. save the api key from the developer.giphy into the repo secrets
# 2. go to .github/workflows/ add as a new file .ymal 
#next 
# 2. the workflow executes the on when ever there is a pull request of type: opened its going to execute the workflow pull request on a opened pull request
# 3. running jobs testing action running on ubuntu-latest 
# 4. permissions: adding the write permission for issues and pull request by default it is read only on the pull_request so a user can post a gif comment (also in dockerfile chmod +X)
# 4.1 permissions is also used for the GITHUB_TOKEN to write, without it by default it only reads on the job level  
# 5. uses:  user has to use the orignal users name, repo and branch >> it allowes the person to use the contents of the full repo, its in main because it got pulled into the main 
# 6. with: github_token is automatically created by the repo just put ${{secrets.}} also GITHUB_REPO_OWNER is built in to the repo 
# 7. with: giphy_api_key add the api key from the developer.giphy into the repo secrets 


#orignal repo is made up of DOCKERFILE, testing.yml, action.yml for the inputs, entrypoint.sh source code




        

# how does it all work ## orginial 
# 1. name the workflow 
# 2. the workflow executes the on when ever there is a pull request of type: opened its going to execute the workflow pull request on a opened pull request
# 3. running jobs testing action running on ubuntu-latest 
# 4. permissions: adding the write permission for issues and pull request by default it is read only on the pull_request so a user can post a gif comment (also in dockerfile chmod +X)
# 4.1 permissions is also used for the GITHUB_TOKEN to write, without it by default it only reads on the job level 
# 5. to access the action.yml, DOCKERFILE, and entrypoint action checkout will allow user to read  and use repo 
# 6. uses: ./ means since the action is part of the same repo you can use users as ./ 
# 7. with: github_token is automatically created by the repo just put ${{secrets.}} also GITHUB_REPO_OWNER is built in to the repo 
# 8. with: giphy_api_key add the api key from the developer.giphy into the repo secrets 
