name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main 
      - 'feature/*'

env: #added 1
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData' 
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}      
jobs:
    unit-testing:
        name: Unit Testing
        services:  #adding 11 service container using database without slowing down system or causing problems info is ephemeral,uses local host to talk to runner, service thru example -u and -p 
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports: 
              - 27017:27017
        env: 
           MONGO_URI: 'mongodb://localhost:27017/superData' 
           MONGO_USERNAME: non-prod-user
           MONGO_PASSWORD: non-prod-password

        strategy: #added 3 from strat >> ex: runs-on and added matrix
          matrix:
            nodejs_version: [18,20]
            operating_system: [ ubuntu-latest ]
            exclude:
              - nodejs_version: 18
                operating_system: macos-latest
        runs-on: ${{ matrix.operating_system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
        
        - name: Setup NodeJS Version - 18
          uses:  actions/setup-node@v6
          with:
            node-version: ${{ matrix.nodejs_version }}
        
        - name: Cache NPM dependencies #add 5
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}


        - name: Install Dependencies 
          run: npm install

        - name: Unit testing 
          run: npm test

        - name: archive Test Result #added 2
          uses: actions/upload-artifact@v7
          with:
            name: Mocha-Test_results
            path: test-results.xml

#added 4

    code-coverage:
      name: Code Coverage
      container: # adding 12 job container, # the node version setup and add the service container to run both no port mapping need it is exposed on the same port and just add the options, with name and out iin the url 
        image: node:18
      services:  
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            options:
              --name mongo
      env: 
           MONGO_URI: 'mongodb://mongo:27017/superData' 
           MONGO_USERNAME: non-prod-user
           MONGO_PASSWORD: non-prod-password
      
      
      
      runs-on: ubuntu-latest
      steps: 
        - name: Check Repository
          uses: actions/checkout@v6
        
      # - name: Setup NodeJS Version - 18
       #  uses: actions/setup-node@v6
        # with:
          # node-version: 18

        - name: Cache NPM dependencies #add 5
          uses: actions/cache@v5
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install Dependencies
          run: npm install
    
        - name: Check Code Coverage
          continue-on-error: true #added 5 expession
          run: npm run coverage

        - name: Archive Test Results
          uses: actions/upload-artifact@v7
          with:
            name: Code-Coverage-Result
            path: coverage 
            retention-days: 5 
      
    #add 6 docker also can do aws ecr 

    docker:
      name: Containerization
      needs: [ unit-testing, code-coverage ]
      permissions:               ##added 11 after fail
        packages: write  
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Dockerhub Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      - name: GHCR Login # added 10 the username and password do not needed to be added its built in
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Docker Build and testing #added 7 no push get file
        uses: docker/build-push-action@v4
        with:
          context: .  #dot means look for dockerfile in the whole directory
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
      

      - name: Docker Image Test #added 8 with a connect to run docker images and action username gets the ip but uses local ip, "live" in the app.js' file means status 
        run: |
          docker images 
          docker run --name solar-system-app -d  \
            -p 3000:3000 \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSSWORD \
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo $IP 

          echo Testing Image URL using wget
          wget -q -O - 127.0.0.1:3000/live | grep live
#
  ##  - name: Docker Build and push # added 9 
    ##   uses: docker/build-push-action@v4
      ## with:
      ##   context: . 
      ##   push: true
      ##   tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}


      - name: Container Registry Push # added 10 part 2
        uses: docker/build-push-action@v4
        with:
          context: . 
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/solar-system${{ github.sha }}